Repository AY2425S1-CS2103-F09-1/tp, pull requests merged in 2024-11, with the labels that each got.

#165 Add Help Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, alpha-bug, feature.help

#172 Improve ContactCard display of details
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: UI

#176 Enforce char limit of 1000 on input command: AddressBookParser
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: alpha-bug

#188 Fix incorrect edit command error message
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: priority.High, alpha-bug, feature.edit

#189 Update message when no contacts found
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: feature.find

#187 Add pagination implementation details to DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#184 Add pagination to UserGuide.md
  docs/UserGuide.md
  docs/images/pagination_ui.png
Labels: priority.High

#182 Refine main window UI
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PaginationPanel.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: UI

#193 Restructure UserGuide.md layout
  docs/UserGuide.md
Labels: priority.High, N.A.

#201 Update sample contacts
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.Medium, severity.Low

#203 Update User Guide on Invalid Contacts, Edit and Help Commands
  docs/UserGuide.md
  docs/images/ExampleJohnDoe.png
Labels: feature.edit, feature.help

#206 Add acknowledgements into DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Low

#234 Remove redundant gradle dependency
  build.gradle
Labels: alpha-bug

#310 Winston junit
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/NameTest.java
  src/test/java/seedu/address/model/contact/NicknameTest.java
  src/test/java/seedu/address/model/contact/RoleTest.java
  src/test/java/seedu/address/model/contact/StudentStatusTest.java
  src/test/java/seedu/address/model/contact/TelegramHandleTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
Labels: Junit

#317 Edited Developer Guide
  docs/DeveloperGuide.md
Labels: [DG Issue]

#318 DG Table of Contents
  docs/DeveloperGuide.md
Labels: [DG Issue]

#312 Fix Grammar and Generalise error message, respond to issue 255
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: DEBATABLE

#326 Added Table of Contents to the UserGuide
  docs/UserGuide.md
Labels: [UG Issue]

#332 Update Planned Enhancements
  docs/DeveloperGuide.md
Labels: [DG Issue]

#337 Added Planned Enhancements
  docs/DeveloperGuide.md
Labels: [DG Issue]

#342 User Guide Cleanup
  docs/UserGuide.md
Labels: [UG Issue]
